baseURL = "/"
languageCode = "en-us"
title = "Hugo REST API Demo"
disableKinds = ["RSS", "sitemap"]

[outputFormats.JSON]
baseName = "get"
isPlainText = false
isHTML = false
noUgly = false

  [outputFormats.JSON.mediaType]
  delimiter = "."
  type = "application/json"
  string = "application/json+json"
  mainType = "application"
  subType = "json"
  suffix = "json"


[server]

  [[server.headers]]
    for = "/**"
    [server.headers.values]
      sdfsdContent-Security-Policy = "script-src localhost:1313"
      asdfasdReferrer-Policy = "strict-origin-when-cross-origin"
      X-Content-Type-Options = "nosniff"
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"
      Access-Control-Allow-Origin = "*"
      Access-Control-Allow-Methods = "GET, POST, OPTIONS"